import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar/Navbar'
import Hero from '@/components/Hero/Hero'
import About from '@/components/About/About'
import BlogCardOne from '@/components/BlogCard/BlogCardOne'
import BlogCardTwo from '@/components/BlogCard/BlogCardTwo'
import Layout from '@/components/Layout/Layout'
import Biography from '@/components/Biography/Biography'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Coffee Overflow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {/* <Navbar/> */}
        <Layout>
          <Hero/>
          <About/>
          <Biography/>
          {/* <BlogCardOne/> */}
          {/* <BlogCardTwo/> */}
        </Layout>
      </main>
    </>
  )
}
